FROM mrcide/squire

# Install chrome
RUN apt install -y default-jre
RUN curl --output /tmp/chrome.deb \
https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
apt install -y /tmp/chrome.deb && rm /tmp/chrome.deb
